### PR TITLE
cards css changed

### PR DESCRIPTION
**Pull request by amansingh1373**

### CODE REVIEW

**Comment by its-me-Harsh-Anand** [comment]
Screenshot_20221006-092821_Chrome

Can you please make updates to mobile view too?

**Comment by amansingh1373** [comment]
@its-me-Harsh-Anand i have made some changes and this was the best i could come up with
mobileview

**Comment by its-me-Harsh-Anand** [comment]
> @its-me-Harsh-Anand i have made some changes and this was the best i could come up with mobileview

Although it requires some more styling, I'm merging it.

Hope you have got 1 PR successfully merged in `Hacktoberfest` and learnt something new.

**Comment by its-me-Harsh-Anand** [comment]
> @its-me-Harsh-Anand i have made some changes and this was the best i could come up with mobileview

Although it requires some more styling, I'm merging it.

Hope you have got 1 PR successfully merged in `Hacktoberfest

**Review by its-me-Harsh-Anand — COMMENTED** [review]
Good start in HacktoberFest

**Pull request merged**
